const PART6_EASY = [
  {id:"p6e_p1",passage:`Dear Mr. Williams,

Thank you for your interest in joining our team at TechCore Solutions. We are pleased to (1)_____ that you have been selected for an interview for the Software Engineer position. The interview will be (2)_____ at our headquarters on March 15th at 2:00 PM.

Please bring two copies of your resume and a valid photo ID. If you (3)_____ to reschedule, please contact us at least 48 hours in advance. We look (4)_____ to meeting you.

Sincerely,
Sarah Park, Human Resources`,
    questions:[
      {id:"p6e1",number:1,text:"(1) _____",options:["A) inform","B) informs","C) informed","D) informing"],answer:"A",explanation:"'Inform' is correct because the fixed phrase 'pleased to + base verb' requires the bare infinitive form, as 'to' here is part of the infinitive construction, not a preposition. 'Informs' is wrong because the third-person singular present form cannot follow an infinitive marker. 'Informed' is wrong because the past participle form does not fit after 'to' in an infinitive construction. 'Informing' is wrong because the gerund or present participle form is only used after prepositions or as part of a progressive verb phrase, not after 'to' as an infinitive marker."},
      {id:"p6e2",number:2,text:"(2) _____",options:["A) held","B) hold","C) holding","D) holds"],answer:"A",explanation:"'Held' is correct because the sentence requires a passive construction ('will be held') where the past participle indicates the interview is the recipient of the action; events are described with 'held' in passive voice. 'Hold' is wrong because the bare infinitive cannot complete the passive structure 'will be ___' without becoming a past participle. 'Holding' is wrong because the present participle would form a progressive, not a passive, and 'will be holding' would imply the interview is actively holding something. 'Holds' is wrong because the third-person singular active form contradicts the passive structure required when describing where an event takes place."},
      {id:"p6e3",number:3,text:"(3) _____",options:["A) need","B) needed","C) are needing","D) needs"],answer:"A",explanation:"'Need' is correct because conditional clauses with 'if' use the present simple tense to describe a possible future situation, and 'you need' is the correct present simple form for second person. 'Needed' is wrong because the simple past tense implies the need already occurred in the past, contradicting the hypothetical future condition described. 'Are needing' is wrong because 'need' is a stative verb and is not normally used in the progressive form in standard written English. 'Needs' is wrong because the third-person singular form does not agree with the second-person subject 'you'."},
      {id:"p6e4",number:4,text:"(4) _____",options:["A) forward","B) ahead","C) up","D) over"],answer:"A",explanation:"'Forward' is correct because 'look forward to' is a fixed phrasal expression meaning to anticipate something positively, and it is the only collocation that completes this idiom. 'Ahead' is wrong because 'look ahead to' is not a standard fixed phrase in formal English correspondence. 'Up' is wrong because 'look up to' means to admire someone, which is semantically unrelated to anticipating a meeting. 'Over' is wrong because 'look over' means to examine or review something, not to express anticipation."}
    ]
  },
  {id:"p6e_p2",passage:`COMPANY ANNOUNCEMENT

Effective January 1st, all employees will be (1)_____ to use the new digital timesheet system. Paper timesheets will no longer be (2)_____.

To access the new system, visit hr.techcore.com and log in (3)_____ your employee ID and password. Training sessions will be (4)_____ every Tuesday at 10 AM in Conference Room B throughout January.`,
    questions:[
      {id:"p6e5",number:1,text:"(1) _____",options:["A) required","B) requesting","C) requested","D) requiring"],answer:"A",explanation:"'Required' is correct because the passive construction 'will be required to' uses a past participle and expresses a mandatory obligation placed on employees; this is the standard form for announcing workplace policies. 'Requesting' is wrong because it is a present participle that would form a progressive verb, meaning employees are in the process of requesting something themselves, which reverses the meaning. 'Requested' is wrong because while it is also a past participle, 'be requested to' expresses a polite invitation rather than a mandatory requirement, which is too weak for this policy announcement. 'Requiring' is wrong because the present participle cannot serve as the past participle in the passive construction 'will be ___ to'."},
      {id:"p6e6",number:2,text:"(2) _____",options:["A) accepted","B) accepting","C) accept","D) acceptable"],answer:"A",explanation:"'Accepted' is correct because the full sentence is 'will no longer be accepted,' a future passive construction where the past participle indicates paper timesheets receive the action of being accepted. 'Accepting' is wrong because the present participle forms a progressive, implying the timesheets are actively accepting something, which is logically incoherent. 'Accept' is wrong because the bare infinitive cannot fill the role of a past participle in a passive verb phrase. 'Acceptable' is wrong because while it is an adjective that could make grammatical sense in isolation, the parallel structure of the announcement—'will be [past participle]'—requires a verb form, not a predicate adjective."},
      {id:"p6e7",number:3,text:"(3) _____",options:["A) using","B) with","C) by","D) through"],answer:"B",explanation:"'With' is correct because the preposition 'with' indicates the instrument or credential used to perform an action, making 'log in with your employee ID' the natural collocational phrase for using credentials. 'Using' is wrong because it is a participle, not a preposition, and while grammatically possible, it is not the most idiomatic fixed phrase for describing login credentials. 'By' is wrong because 'log in by your ID' is not a standard collocational phrase; 'by' indicates means of transportation or agency, not the specific instrument of authentication. 'Through' is wrong because 'log in through' typically refers to accessing a system via a portal or third-party service, not to using a specific credential."},
      {id:"p6e8",number:4,text:"(4) _____",options:["A) held","B) holding","C) hold","D) holds"],answer:"A",explanation:"'Held' is correct because the passive construction 'will be held' uses the past participle to describe a scheduled event, with the subject (training sessions) receiving the action; events and meetings are standardly described with 'held' in passive voice. 'Holding' is wrong because the present participle would form a progressive construction ('will be holding'), implying the sessions are actively holding something rather than being scheduled to take place. 'Hold' is wrong because the bare infinitive cannot complete a passive verb phrase; it would only work in an active construction. 'Holds' is wrong because the third-person singular active form implies sessions actively hold something, contradicting the passive meaning required."}
    ]
  },
  {id:"p6e_p3",passage:`Dear Valued Customer,

Your order #55821 has been (1)_____ and is scheduled for delivery on Thursday, April 10th. You will (2)_____ a confirmation email with a tracking number within 24 hours.

Our delivery team will contact you (3)_____ to the delivery to confirm the time window. If you need to (4)_____ your delivery address, please log in to your account or call us before Wednesday noon.

Thank you for shopping with us!`,
    questions:[
      {id:"p6e9",number:1,text:"(1) _____",options:["A) process","B) processed","C) processing","D) processes"],answer:"B",explanation:"'Processed' is correct because the present perfect passive 'has been processed' requires a past participle, indicating that the order has already completed the action of being processed before the time of writing. 'Process' is wrong because the bare infinitive cannot serve as the past participle in a perfect passive construction. 'Processing' is wrong because the present participle would form 'has been processing,' a present perfect progressive in which the subject (order) is actively doing the processing, which is logically wrong for an inanimate object. 'Processes' is wrong because the third-person singular present active form cannot fill the role of a past participle in a passive construction."},
      {id:"p6e10",number:2,text:"(2) _____",options:["A) receive","B) receiving","C) received","D) reception"],answer:"A",explanation:"'Receive' is correct because modal verbs such as 'will' must be followed by a bare infinitive, and 'you will receive' is the correct future simple active construction for informing the customer about a forthcoming email. 'Receiving' is wrong because a present participle cannot directly follow a modal verb as the main verb without an auxiliary; 'will be receiving' would be grammatically acceptable but is not among the options. 'Received' is wrong because the past participle after 'will' would form a passive construction ('will be received'), but 'be' is missing from the options, and the context requires an active verb with 'you' as agent. 'Reception' is wrong because it is a noun and cannot serve as the main verb of the clause."},
      {id:"p6e11",number:3,text:"(3) _____",options:["A) prior","B) before","C) advance","D) ahead"],answer:"A",explanation:"'Prior' is correct because 'prior to' is a formal prepositional phrase meaning 'before,' and it is the only option here that functions as a preposition governing the noun phrase 'the delivery.' 'Before' is wrong because while 'before' can function as a preposition, the blank is immediately followed by 'to,' making the full phrase 'before to the delivery,' which is ungrammatical. 'Advance' is wrong because it is a noun or adjective (as in 'in advance'), not a preposition, and cannot introduce a noun phrase in this structure. 'Ahead' is wrong because while 'ahead of' can mean 'before,' 'ahead to' is not a grammatical prepositional phrase."},
      {id:"p6e12",number:4,text:"(4) _____",options:["A) update","B) change","C) modify","D) all of the above"],answer:"D",explanation:"'All of the above' is correct because 'update,' 'change,' and 'modify' are all semantically valid verbs for altering a delivery address, and all follow the infinitive marker 'to' correctly in this context. 'Update' alone is not the exclusive answer because the other options are equally correct synonyms in this context. 'Change' alone is not the exclusive answer because 'update' and 'modify' are equally precise alternatives for this action. 'Modify' alone is not the exclusive answer because the question is designed to recognize that all three verbs are appropriate and interchangeable here."}
    ]
  },
  {id:"p6e_p4",passage:`NOTICE TO ALL STAFF

The building fire drill is (1)_____ for Tuesday, May 6th at 2:30 PM. All employees are required to (2)_____ their workstations and proceed to the designated assembly point on the east side of the parking lot.

Please do not use the elevators during the drill. The drill is (3)_____ to last approximately 20 minutes. Department heads are (4)_____ for ensuring all staff members in their teams participate.`,
    questions:[
      {id:"p6e13",number:1,text:"(1) _____",options:["A) schedule","B) scheduled","C) scheduling","D) schedules"],answer:"B",explanation:"'Scheduled' is correct because the passive construction 'is scheduled for' uses the past participle to indicate the drill has been arranged for a specific date; this is the standard way to announce planned events. 'Schedule' is wrong because the bare infinitive cannot serve as the past participle in a passive construction with the linking verb 'is.' 'Scheduling' is wrong because the present participle would form a progressive ('is scheduling'), implying the drill is actively scheduling something, which is logically absurd. 'Schedules' is wrong because the third-person singular active form implies the drill performs the scheduling, which reverses the intended passive meaning."},
      {id:"p6e14",number:2,text:"(2) _____",options:["A) vacate","B) leave","C) exit","D) all of the above"],answer:"D",explanation:"'All of the above' is correct because 'vacate,' 'leave,' and 'exit' are all semantically appropriate verbs meaning to clear or depart from one's workstation, and all three grammatically follow 'required to' as bare infinitives. 'Vacate' alone is not the exclusive answer because the other options convey the same necessary action. 'Leave' alone is not the exclusive answer because 'vacate' and 'exit' are equally valid alternatives. 'Exit' alone is not the exclusive answer because the question recognizes all three as interchangeable in this safety notice context."},
      {id:"p6e15",number:3,text:"(3) _____",options:["A) estimate","B) estimated","C) estimating","D) estimation"],answer:"B",explanation:"'Estimated' is correct because the passive construction 'is estimated to last' uses the past participle to indicate that an external calculation projects the drill's duration; this is the standard phrasing for approximate projections. 'Estimate' is wrong because the bare infinitive cannot serve as the past participle in a passive construction with the linking verb 'is.' 'Estimating' is wrong because the present participle would form a progressive ('is estimating'), suggesting the drill is actively performing an estimation, which is logically incoherent. 'Estimation' is wrong because it is a noun and cannot function as the past participle in a passive verb phrase."},
      {id:"p6e16",number:4,text:"(4) _____",options:["A) responsible","B) accountable","C) both A and B","D) in charge"],answer:"C",explanation:"'Both A and B' is correct because 'responsible for' and 'accountable for' are both standard adjective phrases expressing obligation and duty, and both are grammatically and semantically appropriate in this administrative notice. 'Responsible' alone is not the exclusive answer because 'accountable' is an equally valid and commonly used synonym in professional contexts. 'Accountable' alone is not the exclusive answer because 'responsible' is equally correct and perhaps more commonly used in workplace notices. 'In charge' is wrong because while it can mean having authority, 'in charge for ensuring' is not a standard collocational phrase; one would say 'in charge of ensuring,' but this option does not include 'of,' making it grammatically incorrect as written."}
    ]
  },
  {id:"p6e_p5",passage:`To: All Staff
Subject: New Parking Policy

Beginning March 1st, all employees wishing to park in the company lot must (1)_____ a valid parking permit. Permits are available from the security office on the ground floor.

To obtain a permit, you will need to (2)_____ your employee ID and vehicle registration. Permits are issued free of (3)_____ for permanent staff. Contract staff may obtain permits at a monthly rate of $25. Permits must be (4)_____ on your dashboard at all times.`,
    questions:[
      {id:"p6e17",number:1,text:"(1) _____",options:["A) display","B) hold","C) possess","D) all of the above"],answer:"D",explanation:"'All of the above' is correct because 'display,' 'hold,' and 'possess' all describe having or showing a valid permit, and all function correctly as bare infinitives after the modal 'must.' 'Display' alone is not the exclusive answer because 'hold' and 'possess' are equally valid for describing permit requirements. 'Hold' alone is not the exclusive answer because 'display' and 'possess' are equally applicable. 'Possess' alone is not the exclusive answer because the question acknowledges that all three verbs are appropriate descriptions of the permit requirement."},
      {id:"p6e18",number:2,text:"(2) _____",options:["A) present","B) show","C) provide","D) all of the above"],answer:"D",explanation:"'All of the above' is correct because 'present,' 'show,' and 'provide' all mean to submit or demonstrate identification documents, and all three follow the infinitive marker 'to' grammatically. 'Present' alone is not the exclusive answer because 'show' and 'provide' convey the same meaning in this administrative context. 'Show' alone is not the exclusive answer because 'present' and 'provide' are equally valid and commonly used in formal requests for documents. 'Provide' alone is not the exclusive answer because the question identifies all three as interchangeable verbs for submitting identification."},
      {id:"p6e19",number:3,text:"(3) _____",options:["A) charge","B) cost","C) fee","D) price"],answer:"A",explanation:"'Charge' is correct because 'free of charge' is a fixed idiomatic expression meaning at no cost, and it is the only one of the four options that forms this established phrase. 'Cost' is wrong because 'free of cost' is used in some informal contexts but 'free of charge' is the standard fixed expression in formal written English. 'Fee' is wrong because 'free of fee' is not a recognized idiomatic expression in English. 'Price' is wrong because 'free of price' is not a standard English phrase; the established idiom specifically uses 'charge.'"},
      {id:"p6e20",number:4,text:"(4) _____",options:["A) displayed","B) shown","C) placed","D) all of the above"],answer:"D",explanation:"'All of the above' is correct because 'displayed,' 'shown,' and 'placed' are all past participles that can complete the passive construction 'must be ___ on your dashboard,' and all three accurately describe what should be done with the permit. 'Displayed' alone is not the exclusive answer because 'shown' and 'placed' are equally valid past participles in this passive construction. 'Shown' alone is not the exclusive answer because 'displayed' and 'placed' convey the same required action. 'Placed' alone is not the exclusive answer because the question recognizes all three as appropriate descriptions of how the permit should be positioned on the dashboard."}
    ]
  }
];

const PART6_MEDIUM = [
  {id:"p6m_p1",passage:`To: All Staff
From: Operations Manager
Subject: Office Relocation Update

As previously (1)_____, our company will be relocating to new premises at 200 Technology Park on April 30th. The move is being (2)_____ by MovePro Logistics and is expected to be completed within one business day.

During this transition, some services may be (3)_____ disrupted. We ask for your patience and cooperation. Employees are (4)_____ to pack their personal belongings in the provided boxes by April 25th. Furniture and equipment will be handled by the moving team.`,
    questions:[
      {id:"p6m1",number:1,text:"(1) _____",options:["A) notified","B) announced","C) stated","D) declared"],answer:"B",explanation:"'Announced' is correct because 'as previously announced' is the standard corporate communication phrase used to refer back to an earlier formal disclosure; 'announce' collocates with company news shared publicly or organization-wide. 'Notified' is wrong because 'as previously notified' implies a one-on-one or regulatory notification rather than a broader organizational announcement. 'Stated' is wrong because 'as previously stated' more typically refers to something said within the same document or speech, not a separate prior communication. 'Declared' is wrong because 'declared' carries connotations of legal or official proclamations rather than routine corporate communications."},
      {id:"p6m2",number:2,text:"(2) _____",options:["A) coordinated","B) directed","C) facilitated","D) handled"],answer:"D",explanation:"'Handled' is correct because 'being handled by MovePro Logistics' means the move is being managed and carried out by the logistics company, which is the most natural collocational pairing for physical logistics work. 'Coordinated' is wrong because while it could apply, 'coordinated by' implies organizing multiple parties, whereas the sentence attributes the entire move to one company, suggesting direct execution rather than coordination. 'Directed' is wrong because 'directed by' implies oversight or supervision, typically at a higher managerial level, rather than the hands-on execution a logistics company performs. 'Facilitated' is wrong because 'facilitated by' implies making something easier for others to accomplish, suggesting a supporting role rather than the direct execution of the move."},
      {id:"p6m3",number:3,text:"(3) _____",options:["A) temporarily","B) occasionally","C) permanently","D) periodically"],answer:"A",explanation:"'Temporarily' is correct because the adverb describes a short-term disruption consistent with a one-business-day move, signaling to staff that normal service will resume quickly. 'Occasionally' is wrong because it implies irregular, infrequent disruptions rather than a single, time-limited event tied to the move. 'Permanently' is wrong because it contradicts the context: the disruption is directly tied to the relocation and would logically end once the move is complete. 'Periodically' is wrong because it implies recurring disruptions at intervals, whereas the passage describes a single, bounded relocation event."},
      {id:"p6m4",number:4,text:"(4) _____",options:["A) asked","B) instructed","C) reminded","D) advised"],answer:"B",explanation:"'Instructed' is correct because 'instructed to pack' conveys a direct, formal work directive from management, which is appropriate for a mandatory action employees must complete by a specific deadline. 'Asked' is wrong because 'asked to' implies a polite request rather than a managerial directive, which understates the obligatory nature of packing one's belongings by the deadline. 'Reminded' is wrong because 'reminded to pack' presupposes the packing requirement was already communicated before, whereas the memo presents this as a current instruction. 'Advised' is wrong because 'advised to' suggests a recommendation that employees may choose to follow, whereas the context requires a mandatory directive with a firm deadline."}
    ]
  },
  {id:"p6m_p2",passage:`PERFORMANCE REVIEW POLICY UPDATE

In response to employee feedback, the HR department has (1)_____ several changes to the annual performance review process. These changes are intended to make the review process more transparent and (2)_____.

Beginning this fiscal year, all employees will receive written feedback within five business days of their review meeting. Managers are (3)_____ for ensuring that feedback is specific, actionable, and constructive.

Employees who feel their review was (4)_____ conducted may submit a formal appeal to the HR department within 14 days.`,
    questions:[
      {id:"p6m5",number:1,text:"(1) _____",options:["A) implemented","B) suggested","C) considered","D) debated"],answer:"A",explanation:"'Implemented' is correct because the HR department has already put the changes into effect in response to feedback, making 'implemented' (meaning formally introduced and enacted) the most precise and contextually appropriate choice. 'Suggested' is wrong because it implies the changes are still proposals, contradicting the passage's announcement that changes have already been made. 'Considered' is wrong because it implies the changes are still under evaluation rather than having been officially adopted and applied. 'Debated' is wrong because it implies the changes are contested and unresolved, whereas the passage presents them as finalized policy updates."},
      {id:"p6m6",number:2,text:"(2) _____",options:["A) effective","B) beneficial","C) equitable","D) productive"],answer:"C",explanation:"'Equitable' is correct because it means fair and impartial, which is the most contextually appropriate quality to pair with 'transparent' when describing improvements to a performance review process designed to address employee feedback about fairness. 'Effective' is wrong because while an effective review process is desirable, it does not directly address the concern about fairness that prompted the policy change. 'Beneficial' is wrong because it is too general; it describes any process that produces good outcomes and does not specifically target the fairness concern central to the update. 'Productive' is wrong because it describes efficiency and output, not the fairness and impartiality that the review overhaul is specifically aimed at improving."},
      {id:"p6m7",number:3,text:"(3) _____",options:["A) accountable","B) responsible","C) answerable","D) liable"],answer:"B",explanation:"'Responsible' is correct because 'responsible for ensuring' is the most standard and natural phrasing for assigning professional duties in workplace policy documents. 'Accountable' is wrong because while 'accountable for' is grammatically correct, it typically implies consequences for failure and is used more in performance management contexts than in routine duty assignments. 'Answerable' is wrong because 'answerable for' is less common in formal HR policy and suggests being called to justify actions rather than proactively fulfilling a duty. 'Liable' is wrong because 'liable for' has a legal connotation implying legal responsibility or exposure to penalties, which is too strong for describing a managerial feedback duty."},
      {id:"p6m8",number:4,text:"(4) _____",options:["A) unfairly","B) unjustly","C) improperly","D) incorrectly"],answer:"C",explanation:"'Improperly' is correct because 'improperly conducted' means the review was not carried out according to established procedures and standards, which directly connects to the procedural context of a formal review process. 'Unfairly' is wrong because 'unfairly conducted' focuses on subjective bias rather than procedural violation, which is a narrower concern than the policy language suggests. 'Unjustly' is wrong because it carries a moral or ethical connotation rather than a procedural one, making it less precise in the context of a formal HR appeals process. 'Incorrectly' is wrong because it implies factual error rather than a deviation from procedure, and appeals processes are typically grounded in procedural rather than factual grounds."}
    ]
  },
  {id:"p6m_p3",passage:`MEMORANDUM

TO: All Department Managers
FROM: Finance Department
RE: Q3 Budget Submission

As the third quarter draws to a close, we are (1)_____ all department managers to submit their Q3 budget reports by September 30th. Reports should clearly (2)_____ all expenditures against the approved budget and highlight any significant variances.

Any department that (3)_____ its budget by more than 10% must provide a written explanation. The Finance Department will (4)_____ a consolidated report to the Executive Committee by October 10th.`,
    questions:[
      {id:"p6m9",number:1,text:"(1) _____",options:["A) reminding","B) asking","C) requesting","D) all of the above"],answer:"D",explanation:"'All of the above' is correct because 'reminding,' 'asking,' and 'requesting' are all semantically appropriate present participles for what the Finance Department is doing to prompt managers, and all three form grammatically correct phrases with 'we are ___.' 'Reminding' alone is not the exclusive answer because 'asking' and 'requesting' are equally valid ways to describe the communication. 'Asking' alone is not the exclusive answer because 'reminding' and 'requesting' convey the same intent in this memo context. 'Requesting' alone is not the exclusive answer because the question recognizes all three as interchangeable terms for formally prompting managers to submit reports."},
      {id:"p6m10",number:2,text:"(2) _____",options:["A) outline","B) detail","C) itemize","D) all of the above"],answer:"D",explanation:"'All of the above' is correct because 'outline,' 'detail,' and 'itemize' all mean to list or specify expenditures clearly, and all three follow 'should clearly ___' correctly as bare infinitives. 'Outline' alone is not the exclusive answer because 'detail' and 'itemize' are equally valid verbs for presenting budget expenditures. 'Detail' alone is not the exclusive answer because 'outline' and 'itemize' serve the same function in this financial reporting context. 'Itemize' alone is not the exclusive answer because the question identifies all three verbs as appropriate for clearly presenting expenditure data."},
      {id:"p6m11",number:3,text:"(3) _____",options:["A) exceeds","B) overspends","C) surpasses","D) all of the above"],answer:"D",explanation:"'All of the above' is correct because 'exceeds,' 'overspends,' and 'surpasses' all describe going beyond the approved budget amount, and all three agree with the third-person singular subject 'any department.' 'Exceeds' alone is not the exclusive answer because 'overspends' and 'surpasses' are equally precise synonyms in a budgetary context. 'Overspends' alone is not the exclusive answer because 'exceeds' and 'surpasses' are equally valid verbs for describing budget overrun. 'Surpasses' alone is not the exclusive answer because the question recognizes all three as interchangeable descriptions of spending beyond the budget."},
      {id:"p6m12",number:4,text:"(4) _____",options:["A) submit","B) present","C) distribute","D) all of the above"],answer:"D",explanation:"'All of the above' is correct because 'submit,' 'present,' and 'distribute' are all valid verbs for delivering a consolidated report to the Executive Committee, and all follow the modal 'will' correctly as bare infinitives. 'Submit' alone is not the exclusive answer because 'present' and 'distribute' are equally appropriate verbs for formally delivering a report. 'Present' alone is not the exclusive answer because 'submit' and 'distribute' also accurately describe delivering information to a senior committee. 'Distribute' alone is not the exclusive answer because the question identifies all three as acceptable descriptions of how a consolidated report can be communicated."}
    ]
  },
  {id:"p6m_p4",passage:`Dear Mr. Hoffman,

I am writing to follow up on our meeting last Tuesday regarding the proposed joint venture between Nexus Technologies and your firm. We believe that a (1)_____ between our two companies could be highly beneficial.

Our team has (2)_____ a preliminary proposal, which I have attached for your review. We are particularly interested in (3)_____ on your firm's distribution network in the Asia-Pacific region, while providing our proprietary AI software platform.

We look forward to your feedback and hope to (4)_____ further discussions at your earliest convenience.`,
    questions:[
      {id:"p6m13",number:1,text:"(1) _____",options:["A) partnership","B) collaboration","C) alliance","D) all of the above"],answer:"D",explanation:"'All of the above' is correct because 'partnership,' 'collaboration,' and 'alliance' all describe a mutually beneficial inter-company relationship, and all three are grammatically appropriate nouns in this sentence. 'Partnership' alone is not the exclusive answer because 'collaboration' and 'alliance' convey the same concept of two companies working together. 'Collaboration' alone is not the exclusive answer because 'partnership' and 'alliance' are equally suitable terms for the proposed joint venture. 'Alliance' alone is not the exclusive answer because the question recognizes all three as valid descriptions of the proposed business relationship."},
      {id:"p6m14",number:2,text:"(2) _____",options:["A) prepared","B) developed","C) drafted","D) all of the above"],answer:"D",explanation:"'All of the above' is correct because 'prepared,' 'developed,' and 'drafted' all describe the act of creating a business proposal, and all three form grammatically correct present perfect constructions with 'has ___.' 'Prepared' alone is not the exclusive answer because 'developed' and 'drafted' are equally valid past participles for describing proposal creation. 'Developed' alone is not the exclusive answer because 'prepared' and 'drafted' are equally applicable to the process of producing a business document. 'Drafted' alone is not the exclusive answer because the question identifies all three as appropriate verbs for the creation of a preliminary proposal."},
      {id:"p6m15",number:3,text:"(3) _____",options:["A) leveraging","B) capitalizing","C) building","D) both A and B"],answer:"D",explanation:"'Both A and B' is correct because 'leveraging on' and 'capitalizing on' both mean using an advantage strategically for benefit, and both are appropriate gerunds following the preposition 'in' in 'interested in ___.' 'Leveraging' alone is not the exclusive answer because 'capitalizing on' is an equally valid and commonly used phrase for strategically using another party's assets. 'Capitalizing' alone is not the exclusive answer because 'leveraging' is equally precise for describing strategic use of a distribution network. 'Building' is wrong because 'building on' means to develop or expand from a base, but the context describes using the other firm's network, not constructing upon it, making it a weaker fit than the two correct options."},
      {id:"p6m16",number:4,text:"(4) _____",options:["A) schedule","B) arrange","C) set up","D) all of the above"],answer:"D",explanation:"'All of the above' is correct because 'schedule,' 'arrange,' and 'set up' all mean to organize and plan a meeting, and all three follow the infinitive marker 'to' correctly as bare infinitives. 'Schedule' alone is not the exclusive answer because 'arrange' and 'set up' are equally common verbs for organizing business discussions. 'Arrange' alone is not the exclusive answer because 'schedule' and 'set up' convey the same meaning of planning further discussions. 'Set up' alone is not the exclusive answer because the question recognizes all three as interchangeable expressions for initiating and organizing further meetings."}
    ]
  },
  {id:"p6m_p5",passage:`INTERNAL BULLETIN — IT SECURITY NOTICE

The IT Security team has detected an increase in phishing email attempts (1)_____ at company employees. These emails appear to come from legitimate sources but contain malicious links designed to (2)_____ sensitive information.

Employees are strongly (3)_____ not to click on suspicious links or open attachments from unknown senders. If you receive a suspicious email, please (4)_____ it immediately to security@techcorp.com before deleting it.

Failure to report suspected phishing attempts may (5)_____ to security vulnerabilities affecting all staff.`,
    questions:[
      {id:"p6m17",number:1,text:"(1) _____",options:["A) aimed","B) directed","C) targeted","D) all of the above"],answer:"D",explanation:"'All of the above' is correct because 'aimed at,' 'directed at,' and 'targeted at' all describe phishing attempts designed for a specific audience, and all three function as past participle postmodifiers for 'phishing email attempts.' 'Aimed' alone is not the exclusive answer because 'directed' and 'targeted' are equally precise synonyms for describing intentional focus on a group. 'Directed' alone is not the exclusive answer because 'aimed' and 'targeted' are equally valid descriptions of attacks focused on employees. 'Targeted' alone is not the exclusive answer because the question identifies all three as interchangeable terms for describing intentional attacks on a specific group."},
      {id:"p6m18",number:2,text:"(2) _____",options:["A) steal","B) extract","C) harvest","D) all of the above"],answer:"D",explanation:"'All of the above' is correct because 'steal,' 'extract,' and 'harvest' all describe the illicit obtaining of sensitive data, and all three follow 'designed to ___' correctly as bare infinitives. 'Steal' alone is not the exclusive answer because 'extract' and 'harvest' are equally accurate technical descriptions of data theft. 'Extract' alone is not the exclusive answer because 'steal' and 'harvest' are equally applicable to the malicious acquisition of sensitive information. 'Harvest' alone is not the exclusive answer because the question recognizes all three as valid terms for the unauthorized collection of data from victims."},
      {id:"p6m19",number:3,text:"(3) _____",options:["A) advised","B) cautioned","C) urged","D) all of the above"],answer:"D",explanation:"'All of the above' is correct because 'advised,' 'cautioned,' and 'urged' all convey a strong recommendation or warning, and all three complete the passive construction 'are strongly ___ not to' correctly as past participles. 'Advised' alone is not the exclusive answer because 'cautioned' and 'urged' are equally strong expressions of recommendation in a security notice. 'Cautioned' alone is not the exclusive answer because 'advised' and 'urged' are equally appropriate past participles for expressing a firm security warning. 'Urged' alone is not the exclusive answer because the question identifies all three as valid and interchangeable ways to express a strong organizational recommendation."},
      {id:"p6m20",number:4,text:"(4) _____",options:["A) forward","B) report","C) send","D) all of the above"],answer:"D",explanation:"'All of the above' is correct because 'forward,' 'report,' and 'send' all mean to communicate or transmit a suspicious email to the security team, and all three follow the imperative 'please ___' correctly as bare verb forms. 'Forward' alone is not the exclusive answer because 'report' and 'send' are equally valid instructions for sharing a suspicious email with the security address. 'Report' alone is not the exclusive answer because 'forward' and 'send' are equally appropriate technical actions for transmitting an email to a designated address. 'Send' alone is not the exclusive answer because the question recognizes all three as interchangeable actions for communicating the phishing email to the security team."}
    ]
  }
];

const PART6_HARD = [
  {id:"p6h_p1",passage:`STRATEGIC PARTNERSHIP ANNOUNCEMENT

GlobalTech Industries and Nexus Financial Group are pleased to announce the (1)_____ of a strategic partnership aimed at transforming digital payment infrastructure across Southeast Asia. This collaboration will (2)_____ both companies to leverage their respective strengths.

The partnership, which is (3)_____ to generate over $500 million in combined revenue within three years, will initially focus on developing interoperable payment solutions. Regulatory approvals are currently being (4)_____, with the formal launch scheduled for Q3.`,
    questions:[
      {id:"p6h1",number:1,text:"(1) _____",options:["A) formalization","B) formation","C) foundation","D) fabrication"],answer:"B",explanation:"'Formation' is correct because 'the formation of a partnership' is the standard business phrase for the establishment or creation of a new partnership, and it collocates naturally with 'strategic partnership.' 'Formalization' is wrong because it refers to making something official that already exists informally, whereas this announcement describes the creation of something new. 'Foundation' is wrong because it refers to the base or underlying principle of something, or to a non-profit organization; while metaphorically possible, 'the foundation of a partnership' is not standard business English for announcing a new arrangement. 'Fabrication' is wrong because it means the making of something by assembly, or more commonly, the invention of a falsehood; neither meaning is appropriate for announcing a genuine business partnership."},
      {id:"p6h2",number:2,text:"(2) _____",options:["A) allow","B) permit","C) enable","D) authorize"],answer:"C",explanation:"'Enable' is correct because 'enable companies to leverage' specifically means to give capability or make it possible for them to use their strengths, which is the precise meaning required by the context of a strategic collaboration. 'Allow' is wrong because while grammatically acceptable, 'allow' carries a connotation of granting permission rather than providing capability, making it less precise than 'enable' for describing the empowering effect of a collaboration. 'Permit' is wrong because it implies giving legal or official permission, which is too regulatory a connotation for describing the benefits of a business collaboration. 'Authorize' is wrong because it specifically means to give official sanction or legal authority, which implies a top-down permission structure inappropriate for describing how a partnership benefits two equal companies."},
      {id:"p6h3",number:3,text:"(3) _____",options:["A) projected","B) anticipated","C) estimated","D) forecasted"],answer:"A",explanation:"'Projected' is correct because 'projected to generate' is the standard forward-looking financial language used in business announcements to state expected future revenue figures based on analysis. 'Anticipated' is wrong because while it can describe expected outcomes, 'anticipated to generate' is less commonly used in financial reporting; 'anticipated' more naturally takes a noun clause ('it is anticipated that') rather than an infinitive. 'Estimated' is wrong because 'estimated' typically expresses approximation of a current or past quantity rather than a forward-looking financial projection. 'Forecasted' is wrong because while 'forecasted' can describe financial predictions, 'projected' is the more standard term in corporate announcement language for revenue targets."},
      {id:"p6h4",number:4,text:"(4) _____",options:["A) sought","B) applied","C) requested","D) petitioned"],answer:"A",explanation:"'Sought' is correct because 'approvals being sought' is the standard legal and corporate phrasing meaning approvals are being actively pursued; 'seek' is the established verb collocated with 'regulatory approvals' in corporate communications. 'Applied' is wrong because 'applied' implies submitting a formal application, whereas 'sought' conveys the broader ongoing pursuit of approvals, which may involve multiple strategies beyond formal applications. 'Requested' is wrong because 'requested' implies a single formal request has been made, whereas 'sought' conveys an active and ongoing process of pursuing regulatory approval. 'Petitioned' is wrong because 'petitioned' carries a connotation of formal appeals or advocacy, typically used in legal or governmental contexts, rather than the routine corporate regulatory approval process described."}
    ]
  },
  {id:"p6h_p2",passage:`RISK MANAGEMENT CIRCULAR

To: All Senior Management
Re: Cybersecurity Protocol Enhancement

In light of (1)_____ cyber threats targeting financial institutions globally, the Board of Directors has mandated the immediate implementation of enhanced cybersecurity protocols. Effective immediately, all data access must be (2)_____ through multi-factor authentication systems.

The IT Security team has been (3)_____ with conducting a comprehensive vulnerability assessment of all critical systems. Results are to be (4)_____ to the Risk Committee no later than the end of the current quarter. Non-compliance may result in disciplinary action.`,
    questions:[
      {id:"p6h5",number:1,text:"(1) _____",options:["A) escalating","B) proliferating","C) intensifying","D) mounting"],answer:"D",explanation:"'Mounting' is correct because 'mounting threats' describes a gradual and accumulating increase in danger, which precisely captures the sustained buildup of cyber threats that justifies an urgent board mandate. 'Escalating' is wrong because while it means increasing, it implies a rapid and sudden rise rather than the sustained accumulation conveyed by 'mounting,' making it slightly less precise in this corporate risk context. 'Proliferating' is wrong because it specifically means multiplying in number or variety, which focuses on the spread rather than the increasing severity of threats, a nuance that does not best fit the risk management context. 'Intensifying' is wrong because it describes threats growing more severe in force, whereas the circular's concern is about accumulating and growing threats over time, which 'mounting' better captures."},
      {id:"p6h6",number:2,text:"(2) _____",options:["A) authenticated","B) authorized","C) validated","D) verified"],answer:"B",explanation:"'Authorized' is correct because 'authorized through multi-factor authentication' means data access is granted permission through the MFA system, and 'authorized' is the standard security term for permission-based access control. 'Authenticated' is wrong because while authentication is a component of MFA, 'authenticated through' describes the process of verifying identity, whereas 'authorized' more correctly describes the granting of access rights that results from that process. 'Validated' is wrong because 'validated' refers to confirming the legitimacy of data or processes, not to granting access permissions to users of a system. 'Verified' is wrong because it describes the confirmation of information as accurate, not the granting of system access; verification is a step in authentication, not the access permission itself."},
      {id:"p6h7",number:3,text:"(3) _____",options:["A) entrusted","B) tasked","C) assigned","D) charged"],answer:"B",explanation:"'Tasked' is correct because 'tasked with conducting' is the standard corporate expression for formally assigning a specific responsibility to a team or individual, and it is the most common collocational phrase in business and organizational writing. 'Entrusted' is wrong because 'entrusted with' carries a connotation of delegating something valuable or sensitive with implied trust, which is more personal than the formal assignment described in a risk management circular. 'Assigned' is wrong because while 'assigned to conduct' is grammatically possible, 'assigned with' is not idiomatic; the standard phrasing is 'assigned to,' making this option problematic in the given structure. 'Charged' is wrong because 'charged with' can mean either formally accused of something or formally given a responsibility, creating ambiguity that 'tasked with' avoids in a professional context."},
      {id:"p6h8",number:4,text:"(4) _____",options:["A) presented","B) submitted","C) reported","D) relayed"],answer:"B",explanation:"'Submitted' is correct because 'submitted to the Risk Committee' is the formal process for delivering official findings or documents through the proper organizational channel, which is the appropriate register for a board-level risk management circular. 'Presented' is wrong because 'presented to' implies an oral or visual delivery, such as a meeting presentation, whereas a vulnerability assessment result would be formally submitted as a written document. 'Reported' is wrong because 'reported to the committee' implies an informal or ongoing status update rather than the formal, one-time delivery of completed assessment findings. 'Relayed' is wrong because 'relayed' suggests passing on information from a third party, implying the deliverer is an intermediary, whereas the IT Security team is directly responsible for producing and delivering the results."}
    ]
  },
  {id:"p6h_p3",passage:`ANNUAL GENERAL MEETING — SHAREHOLDER NOTICE

Pursuant to Article 12 of the Company's Articles of Association, notice is hereby (1)_____ that the Annual General Meeting of Meridian Holdings plc will be held on June 25th at 10:00 AM at the Meridian Tower, 100 Financial Square.

Shareholders of record as of May 31st are (2)_____ to attend and vote. The following resolutions will be put to shareholders: approval of the annual financial statements, re-election of directors, and (3)_____ of the external auditor.

Shareholders unable to attend in person may (4)_____ their vote by submitting a proxy form no later than 48 hours before the meeting.`,
    questions:[
      {id:"p6h9",number:1,text:"(1) _____",options:["A) given","B) issued","C) served","D) all of the above"],answer:"D",explanation:"'All of the above' is correct because 'given,' 'issued,' and 'served' are all standard verbs used in formal legal and corporate notice language to describe the act of formally communicating an official notice. 'Given' alone is not the exclusive answer because 'issued' and 'served' are equally standard in formal notice drafting. 'Issued' alone is not the exclusive answer because 'given' and 'served' are equally recognized legal terms for the formal communication of a notice. 'Served' alone is not the exclusive answer because the question identifies all three as valid and interchangeable verbs in the formal language of corporate legal notices."},
      {id:"p6h10",number:2,text:"(2) _____",options:["A) entitled","B) eligible","C) qualified","D) all of the above"],answer:"D",explanation:"'All of the above' is correct because 'entitled,' 'eligible,' and 'qualified' all convey the right of registered shareholders to attend and vote at the AGM, and all three are grammatically correct predicate adjectives in this context. 'Entitled' alone is not the exclusive answer because 'eligible' and 'qualified' are equally valid terms for describing the voting and attendance rights of registered shareholders. 'Eligible' alone is not the exclusive answer because 'entitled' and 'qualified' convey the same meaning of meeting the criteria to participate. 'Qualified' alone is not the exclusive answer because the question recognizes all three as appropriate terms for describing shareholder participation rights."},
      {id:"p6h11",number:3,text:"(3) _____",options:["A) appointment","B) reappointment","C) ratification","D) all of the above"],answer:"B",explanation:"'Reappointment' is correct because the external auditor already holds the position and the AGM resolution concerns renewing or continuing their mandate, which is described as 'reappointment' in standard corporate governance and AGM agenda language. 'Appointment' is wrong because it would imply the auditor is being selected for the first time, whereas an external auditor typically serves ongoing terms that must be renewed at each AGM. 'Ratification' is wrong because it means formally approving something already done, such as ratifying a decision made outside a formal meeting; it is not the standard AGM term for the auditor renewal resolution. 'All of the above' is wrong because 'appointment' and 'ratification' do not accurately describe the renewal of an existing auditor's mandate, making 'reappointment' the only precisely correct term."},
      {id:"p6h12",number:4,text:"(4) _____",options:["A) exercise","B) cast","C) register","D) all of the above"],answer:"D",explanation:"'All of the above' is correct because 'exercise,' 'cast,' and 'register' are all standard verbs used in corporate governance and electoral contexts to describe the act of submitting a vote. 'Exercise' alone is not the exclusive answer because 'cast' and 'register' are equally recognized terms for the voting procedure described. 'Cast' alone is not the exclusive answer because 'exercise' and 'register' are equally valid verbs in the formal language of shareholder voting. 'Register' alone is not the exclusive answer because the question identifies all three as appropriate verbs for the act of formally recording or submitting a vote through a proxy form."}
    ]
  },
  {id:"p6h_p4",passage:`EXECUTIVE SUMMARY: MARKET ENTRY FEASIBILITY REPORT

This report has been (1)_____ by the Strategy Division to assess the viability of entering the Indian consumer electronics market. Our analysis draws on primary market research, competitor intelligence, and regulatory assessments conducted over a six-month period.

The Indian market presents a (2)_____ opportunity, driven by a growing middle class, increasing smartphone penetration, and supportive government policies. However, (3)_____ barriers including complex customs regulations, local content requirements, and intense domestic competition must be carefully (4)_____ before any market entry decision is finalized.`,
    questions:[
      {id:"p6h13",number:1,text:"(1) _____",options:["A) commissioned","B) prepared","C) compiled","D) all of the above"],answer:"D",explanation:"'All of the above' is correct because 'commissioned,' 'prepared,' and 'compiled' all accurately describe the creation of a formal executive report, and all three form grammatically correct present perfect passive constructions with 'has been ___.' 'Commissioned' alone is not the exclusive answer because 'prepared' and 'compiled' are equally valid descriptions of how a formal report is produced. 'Prepared' alone is not the exclusive answer because 'commissioned' and 'compiled' are equally applicable verbs for the production of a feasibility report. 'Compiled' alone is not the exclusive answer because the question recognizes all three as appropriate terms for the creation and production of a formal business report."},
      {id:"p6h14",number:2,text:"(2) _____",options:["A) compelling","B) substantial","C) significant","D) all of the above"],answer:"D",explanation:"'All of the above' is correct because 'compelling,' 'substantial,' and 'significant' all describe the strength and importance of the market opportunity, and all three are appropriate adjectives in this executive summary context. 'Compelling' alone is not the exclusive answer because 'substantial' and 'significant' are equally valid adjectives for describing a strong market opportunity. 'Substantial' alone is not the exclusive answer because 'compelling' and 'significant' are equally precise descriptors of the market's attractiveness. 'Significant' alone is not the exclusive answer because the question identifies all three as interchangeable qualifiers for describing a major business opportunity."},
      {id:"p6h15",number:3,text:"(3) _____",options:["A) notable","B) considerable","C) significant","D) all of the above"],answer:"D",explanation:"'All of the above' is correct because 'notable,' 'considerable,' and 'significant' all quantify the severity of the market entry barriers, and all three are grammatically appropriate adjectives modifying 'barriers' in this context. 'Notable' alone is not the exclusive answer because 'considerable' and 'significant' are equally suitable adjectives for describing the scale of the barriers. 'Considerable' alone is not the exclusive answer because 'notable' and 'significant' are equally valid descriptors of barriers that warrant careful analysis. 'Significant' alone is not the exclusive answer because the question recognizes all three as interchangeable adjectives for indicating that the barriers are serious and must be carefully addressed."},
      {id:"p6h16",number:4,text:"(4) _____",options:["A) addressed","B) navigated","C) mitigated","D) all of the above"],answer:"D",explanation:"'All of the above' is correct because 'addressed,' 'navigated,' and 'mitigated' all describe appropriate strategies for dealing with market entry barriers, and all three follow 'must be carefully ___' correctly as past participles in a passive construction. 'Addressed' alone is not the exclusive answer because 'navigated' and 'mitigated' are equally valid verbs for describing how barriers are managed. 'Navigated' alone is not the exclusive answer because 'addressed' and 'mitigated' are equally applicable strategies for dealing with regulatory and competitive barriers. 'Mitigated' alone is not the exclusive answer because the question identifies all three as appropriate and interchangeable descriptions of managing market entry challenges."}
    ]
  },
  {id:"p6h_p5",passage:`BOARD RESOLUTION — SHARE REPURCHASE PROGRAM

BE IT RESOLVED that the Board of Directors hereby (1)_____ the buyback of up to 5% of the Company's issued ordinary shares over the next twelve months. This program is (2)_____ upon the Company maintaining a minimum cash reserve of $50 million at all times.

The Finance Director is (3)_____ to execute purchases at market prices deemed favorable by the treasury team. All repurchased shares shall be (4)_____ as treasury shares and may, at the Board's discretion, be cancelled or reissued in connection with the Company's employee equity incentive plan.`,
    questions:[
      {id:"p6h17",number:1,text:"(1) _____",options:["A) authorizes","B) approves","C) sanctions","D) all of the above"],answer:"D",explanation:"'All of the above' is correct because 'authorizes,' 'approves,' and 'sanctions' are all interchangeable verbs in the formal language of board resolutions, each meaning to officially grant permission for the described action. 'Authorizes' alone is not the exclusive answer because 'approves' and 'sanctions' are equally standard verbs in board resolution language. 'Approves' alone is not the exclusive answer because 'authorizes' and 'sanctions' are equally valid expressions of official corporate approval. 'Sanctions' alone is not the exclusive answer because the question identifies all three as appropriate and interchangeable terms for expressing the board's official endorsement."},
      {id:"p6h18",number:2,text:"(2) _____",options:["A) conditional","B) contingent","C) subject","D) both B and C"],answer:"D",explanation:"'Both B and C' is correct because 'contingent upon' and 'subject to' are both standard conditional legal expressions used in board resolutions and contracts to indicate that a program depends on a specified condition being met. 'Conditional' is wrong because while 'conditional on' is grammatically possible, it is less common than 'contingent upon' or 'subject to' in formal legal and corporate resolution language, and in the blank it would require 'on' rather than 'upon' to be idiomatic. 'Contingent' alone is not the exclusive answer because 'subject to' is equally standard and both options are correct. 'Subject' alone is not the exclusive answer because 'contingent upon' is equally valid in this legal context, making both B and C correct."},
      {id:"p6h19",number:3,text:"(3) _____",options:["A) authorized","B) empowered","C) mandated","D) both A and B"],answer:"D",explanation:"'Both A and B' is correct because 'authorized to execute' and 'empowered to execute' both mean the Finance Director has been officially granted the right and capability to carry out purchase transactions, and both are standard in corporate resolution and delegation language. 'Authorized' alone is not the exclusive answer because 'empowered' is equally standard for delegating the right to act. 'Empowered' alone is not the exclusive answer because 'authorized' is equally precise for granting official permission to execute transactions. 'Mandated' is wrong because 'mandated to' implies a compulsory duty imposed from above, whereas the resolution is granting the Finance Director the discretionary right to act, not ordering them to do so unconditionally."},
      {id:"p6h20",number:4,text:"(4) _____",options:["A) classified","B) held","C) designated","D) all of the above"],answer:"D",explanation:"'All of the above' is correct because 'classified,' 'held,' and 'designated' as treasury shares are all standard accounting and legal terms used to describe the treatment of repurchased shares, and all three form grammatically correct passive constructions with 'shall be ___.' 'Classified' alone is not the exclusive answer because 'held' and 'designated' are equally valid accounting terms for the treatment of treasury shares. 'Held' alone is not the exclusive answer because 'classified' and 'designated' are equally precise terms in corporate finance for the status of repurchased shares. 'Designated' alone is not the exclusive answer because the question recognizes all three as appropriate and interchangeable accounting descriptions for repurchased shares held by the company."}
    ]
  }
];
